server:
  port: 80
spring:
  application:
    name:  consul-comsumer-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
