server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/payment?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#  instance:
#    instance-id: payment8002
#    prefer-ip-address: true
  cloud:
    zookeeper:
      connect-string: 127.0.0.1.2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atgugu.springcloud.entities